#!/usr/bin/env ruby
#
# Author: rasan@nyu.edu

require 'json'
require 'net/http'
require 'open3'
require 'optparse'
require 'uri'
require 'yaml'


ros_stone_bin = "/Users/dlts/Desktop/RosarioStone2016.pl"

jhove_bin = "/usr/local/dlib/jhove-tools/jhove-tif-batch.sh"

ccg_text_check  = %w[image_set image postcard map book]
ros_stone_check = %w[image_set image postcard map book]
jhove_check     = %w[image_set image postcard map book]


def do_cmd(cmd)
  output, status = Open3.capture2e(cmd)
  success = status.exitstatus.zero?
  if !success || cmd =~ /^ccg/ && output =~ /^fail,/
    raise "#{cmd} exited unsuccessfully: #{output}"
  end
end

config = YAML.load_file('config.yaml')

op = OptionParser.new do |opts|

  opts.banner = "Usage: #{$0} ID INPUT_DIRECTORY OBJECT_TYPE"

  opts.on('-h', '--help', 'Print help message') do
    STDERR.puts opts
    exit
  end

end

op.parse!

if ARGV.size != 3
  STDERR.puts "Wrong number of arguments.\n", op
  exit 1
end

id, input_dir, obj_type = ARGV.first(3)

if !File.directory?(input_dir)
  raise "Input directory #{input_dir} does not exist"
end

obj_type = 'book'

tracking_url_file = File.join(input_dir, 'tracking_url')
if File.file?(tracking_url_file)
  tracking_url = File.open(tracking_url_file).first.strip
  uri = URI.parse(tracking_url)
  http = Net::HTTP.new(uri.host, uri.port)
  request = Net::HTTP::Get.new(uri.request_uri)
  request.basic_auth(config[:rsbe_user], config[:rsbe_pass])
  response = http.request(request)
  tracking = JSON.parse(response.body)
  obj_type = tracking['object_type']
end

if ccg_text_check.include?(obj_type)
  do_cmd("ccg text check -p #{id} -d #{input_dir}")
end

if ros_stone_check.include?(obj_type)
  do_cmd("#{ros_stone_bin} #{input_dir}")
end

if jhove_check.include?(obj_type)
  do_cmd("#{jhove_bin} #{input_dir}")
end

